[package]
name = "chipioindustries/remotes"
description = "A handler for RemoteEvent and RemoteFunction instances."
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Llama = "freddylist/llama@1.1.1"
Rapscallion = "chipioindustries/rapscallion@1.0.4"
Signal = "chipioindustries/signal@1.0.3"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"