[package]
name = "chipioindustries/remotes"
description = "A handler for RemoteEvent and RemoteFunction instances."
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["docs", ".github", "DevPackages", "Packages", "test", ".gitignore", "CHANGELOG.md", "foreman.toml", "getLatestChangelog.py", "LICENSE", "README.md", "selene.toml", "testez.toml", "wally.exe", "yarn.lock"]
include = ["src", "wally.toml", "wally.lock", "default.project.json"]

[dependencies]
Llama = "freddylist/llama@1.1.1"
Rapscallion = "chipioindustries/rapscallion@1.0.4"
Signal = "chipioindustries/signal@1.0.3"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"